#!/usr/bin/env python3
"""
Node Agent — Chat Node — User Interface / Communication
Auto-generated by swarm_provision.py

Role: Manages voice I/O, TTS/STT, conversational state. The user-facing layer of the swarm.
"""

import asyncio
import json
import logging
import os
import sys
import time
from pathlib import Path

# Add directories to path (swarm_node.py may be in the main project dir)
sys.path.insert(0, "/home/jimmy/teamwork_projects/xbox_ai_agent")
sys.path.insert(0, "/home/jimmy/swarm_node")
sys.path.insert(0, str(Path(__file__).parent))

from swarm_node import SwarmNode, SwarmClient

# Load configuration
CONFIG_PATH = Path(__file__).parent / "config" / "node.json"
with open(CONFIG_PATH) as f:
    CONFIG = json.load(f)

# Setup logging
logging.basicConfig(
    level=getattr(logging, CONFIG["logging"]["level"]),
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler(CONFIG["paths"]["logs_dir"] + "/node.log"),
    ],
)
logger = logging.getLogger("node.chat-node")


class ChatNodeAgent:
    """Swarm agent handling chat-node tasks."""

    def __init__(self):
        self.node = SwarmNode(
            host=CONFIG["network"]["bind_host"],
            port=CONFIG["network"]["bind_port"],
        )
        self.orchestrator_host = CONFIG["network"]["orchestrator_host"]
        self.orchestrator_port = CONFIG["network"]["orchestrator_port"]
        self.role = "chat-node"
        self._running = False

    async def start(self):
        """Start the node and register with orchestrator."""
        logger.info(f"Starting {self.role} node...")
        logger.info(f"Orchestrator: {self.orchestrator_host}:{self.orchestrator_port}")

        self._register_handlers()
        await self.node.start()
        logger.info(f"{self.role} node started on port {self.node.port}")

        await self._register_with_orchestrator()

        self._running = True
        while self._running:
            await asyncio.sleep(1)

    def _register_handlers(self):
        """Register task handlers for this role."""
        self.node.register_handler("chat", self._handle_chat)
        self.node.register_handler("stt", self._handle_stt)
        self.node.register_handler("tts", self._handle_tts)

    async def _register_with_orchestrator(self):
        """Register this node with the orchestrator."""
        try:
            client = SwarmClient(self.orchestrator_host, self.orchestrator_port)
            await client.connect()
            await client.send("register", {
                "role": self.role,
                "hostname": CONFIG["hostname"],
                "port": self.node.port,
                "platform": CONFIG["platform"],
                "features": CONFIG["features"],
            })
            await client.close()
            logger.info("Registered with orchestrator successfully")
        except Exception as e:
            logger.warning(f"Could not register with orchestrator: {e}")
            logger.info("Will retry on first task...")

    async def _handle_chat(self, args):
        """Handle chat requests."""
        message = args[0] if args else ""
        return {"status": "success", "response": f"[chat-node] Processing: {message}"}

    async def _handle_stt(self, args):
        """Handle speech-to-text requests."""
        return {"status": "success", "text": "STT placeholder"}

    async def _handle_tts(self, args):
        """Handle text-to-speech requests."""
        return {"status": "success", "audio": "TTS placeholder"}

    async def stop(self):
        """Stop the node gracefully."""
        self._running = False
        await self.node.stop()
        logger.info(f"{self.role} node stopped")


async def main():
    """Main entry point."""
    agent = ChatNodeAgent()

    loop = asyncio.get_event_loop()
    for sig in ("SIGINT", "SIGTERM"):
        try:
            loop.add_signal_handler(
                getattr(__import__("signal"), sig),
                lambda: asyncio.create_task(agent.stop()),
            )
        except (NotImplementedError, AttributeError):
            pass

    try:
        await agent.start()
    except KeyboardInterrupt:
        logger.info("Shutting down...")
        await agent.stop()


if __name__ == "__main__":
    asyncio.run(main())
